- name: add repository
  yum_repository:
    name: grafana
    description: grafana YUM repsoitory
    baseurl: "https://packagecloud.io/grafana/stable/el/7/$basearch"
    gpgkey: https://packagecloud.io/gpg.key https://grafanarel.s3.amazonaws.com/RPM-GPG-KEY-grafana
    gpgcheck: yes

- name: install grafana
  yum:
    name: grafana
    state: latest

- name: publish grafana.ini
  copy:
    src: grafana.ini
    dest: /etc/grafana/grafana.ini
    owner: root
    group: grafana
    mode: 0440

- name: start grafana server
  service:
    name: grafana-server
    state: restarted
    enabled: yes
