- name: install docker
  apt:
    name: docker.io
    state: latest

- name: install ansible via apt
  apt:
    name: ansible
    state: latest

- name: install docker-py
  pip:
    name: docker-py
    state: latest

- name: update system
  apt:
    update_cache: yes
    upgrade: dist