version: '3'
services:
  multithreading:
    image: "ollihoo/multithreading:latest"
    container_name: "multithreading"
    depends_on:
     -  telegraf
    ports:
     - "8081:8080"
    volumes:
     - "./localhost:/config:ro"

  influxdb:
    image: "influxdb"
    container_name: "influxdb"
    ports:
     - "8086:8086"
    volumes:
     - "./influxdb:/var/lib/influxdb"

  grafana:
    image: "grafana/grafana"
    container_name: "grafana"
    depends_on:
     - influxdb
    environment:
     - GF_PATHS_CONFIG=/var/lib/grafana/grafana.ini
    ports:
     - "3000:3000"
    volumes:
     - "./grafana:/var/lib/grafana"
    links:
      - "influxdb:influxdb"

  telegraf:
    image: "telegraf"
    container_name: "telegraf"
    depends_on:
     - influxdb
    volumes:
     - "./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro"
