- name: create data directory and set user rights
  file:
    path: /var/jenkins_home
    owner: root
    group: root
    mode: 0777

- name: Restart a container
  docker_container:
    name: jenkins
    image: jenkins/jenkins:lts
    state: started
    restart: yes
    volumes:
      - "/var/jenkins_home:/var/jenkins_home"
    published_ports:
      - "8080:8080"
      - "50000:50000"