- name: add influx repository
  yum_repository:
    name: influxdb
    description: "InfluxDB Repository - RHEL $releasever"
    baseurl: "https://repos.influxdata.com/rhel/$releasever/$basearch/stable"
    gpgkey: https://repos.influxdata.com/influxdb.key
    gpgcheck: yes

- name: install influxdb
  yum:
    name: influxdb
    state: latest

- name: start influxdb
  service:
    name: influxdb
    state: restarted
    enabled: yes
